name: SimpleBroadcast
version: 1.0.0
main: fr.trisout.simplebroadcast.Main
commands:
  broadcast:
    permission: simplebroadcast.broadcast.use
    description: broadcast command
  announcement:
    permission: simplebroadcast.announcement.use
    description: annonce command